# YAML file for Frontend prod Deployments and Services
# YAML to deploy latest Frontend image pushed to the Azure Container Repository for Frontend prod images and allow communication over container port 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyp-frontend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: fyp-frontend-prod
  template:
    metadata:
      labels:
        deployment-name: fyp-frontend-prod
    spec:
      containers:
        - name: fyp-frontend-prod
          image: acrfypianh.azurecr.io/fyp-ianh-frontend-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
# YAML to deploy loadbalancer for the Frontend mapping incoming port 80 to target port 80 for the Frontend deployment named "fyp-frontend-prod"
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: covid-vaccine-registration-prod
  labels:
    service-label: fyp-frontend-cluster-service-prod
  name: fyp-frontend-cluster-service-loadbalancer-prod
spec:
  type: LoadBalancer
  ports:
  - name: fyp-frontend-load-balancer-service-port-prod
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    deployment-name: fyp-frontend-prod
---
#  YAML to deploy Horizontal Pod Autoscaler for the Frontend "fyp-frontend-prod" that will scale the Frontend from 1 to 5 replicas if allocated CPU utilization for a container exceeds 50%
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fyp-frontend-prod-hpa
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fyp-frontend-prod
  targetCPUUtilizationPercentage: 50 # target CPU utilization
